server:
  port: 8081
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000


spring:
  application:
    name: sapi-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sapi
    username: root
    password: abc123
  session:
    timeout: 86400
    redis:
      namespace: "spring:session" # spring boot 2.4 is namespace but 2.3 is store-type=redis
  data:
    redis:
      database: 1
      host: localhost
      port: 6379
      timeout: 5000


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名，对应着数据库的字段
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.shooter.sapibackend.controller
sapi:
  client:
    access-key: shooter
    secret-key: abcdefg


dubbo:
  application:
    name: dubbo-springboot-demo-consumer
    qosEnable: false
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
